### PR TITLE
feat: validate groups and kinds, fix double processing

### LINKED ISSUE #262: refactor: ProcessAPIConfig called twice
The ProcessAPIConfig does a lot of method including parsing and pulling of markers.  During a debug sessions, I found that this method is called twice which results in potentially duplication of an intense loop.

1. https://github.com/vmware-tanzu-labs/operator-builder/blob/main/internal/plugins/config/v1/api.go#L49 : this gets called first
2. https://github.com/vmware-tanzu-labs/operator-builder/blob/main/internal/plugins/workload/v1/api.go#L60 : this gets called second

I believe we should export the `createAPISubcommand` type (`CreateAPISubcommand`) and use it in both of these packages and do everything up front (item 1 above) and remove the extra calls.  This would allow us to validate and set the workload only a single time and remove the second loop.

### LINKED ISSUE #270: feat: validate duplicate kinds within groups
Consider the following workload configs:

`mything.yaml`:

```yaml
---
kind: ComponentWorkload
name: my-thing
spec:
  api:
    clusterScoped: false
    domain: my.domain
    group: stuff
    kind: MyThing
    version: v1alpha1
  companionCliSubcmd:
    description: Manage my thing
    name: my-thing
  dependencies: []
  resources:
    - postgres.yaml
```

`mything2.yaml`:

```yaml
---
kind: ComponentWorkload
name: my-thing-2
spec:
  api:
    clusterScoped: false
    domain: my.domain
    group: stuff
    kind: MyThing
    version: v1alpha1
  companionCliSubcmd:
    description: Manage my second thing
    name: my-thing
  dependencies: []
  resources:
    - redis.yaml
```

Although these were meant to me independent components, operator-builder sees them as the same kind and builds them under the same `_types.go` file and `resources/` directory.

We should validate that there are no duplicate kinds within their individual groups and return and error when we find this problem.

### PR DESCRIPTION
**Pull request by scottd018**
This PR improves a few items of interest:

- Fixes #270 - Validates that component kinds are unique within the groups
- Fixes #262 - Removes double parsing of entire resource manifests
- Refactors files into their own independent packages

### CODE REVIEW

File: internal/workload/v1/resources/child.go [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+	"github.com/vmware-tanzu-labs/operator-builder/internal/workload/v1/markers"
+)
+
+var (
+	ErrChildResourceResourceMarkerInspect = errors.New("error inspecting resource markers for child resource")
+	ErrChildResourceResourceMarkerProcess = errors.New("error processing resource markers for child resource")
+)
+
+// Child contains attributes for resources created by the custom resource.
+// These definitions are inferred from the resource manifests.  They can be thought
```
Comment (lander2k2) [inline internal/workload/v1/resources/child.go:19]:
```suggestion
// These definitions are inferred from the resource manifests supplied to
```

File: internal/workload/v1/resources/child.go [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+// of as the individual resources which are managed by the controller during
+// reconciliation and represent all resources which are passed in via the `spec.resources`
```
Comment (lander2k2) [inline internal/workload/v1/resources/child.go:21]:
```suggestion
// configuration.  They are the resources that are managed by the controller
```

File: internal/workload/v1/resources/child.go [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+// field of the workload configuration.
```
Comment (lander2k2) [inline internal/workload/v1/resources/child.go:22]:
```suggestion
// during reconciliation.
```

File: internal/workload/v1/resources/source_file.go [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+import (
+	"fmt"
+	"path/filepath"
+	"strings"
+
+	"github.com/vmware-tanzu-labs/operator-builder/internal/utils"
+)
+
+// SourceFile represents a golang source code file that contains one or more
+// child resource objects.
```
Comment (lander2k2) [inline internal/workload/v1/resources/source_file.go:15]:
```suggestion
// child resource objects in the destination project being generated by operator-builder.
```

**Comment by lander2k2** [comment]
Naming suggestions for the `internal/workload/v1/resources` package...
```
internal/workload/v1/
...
└── child_resources
    ├── child_resources.go
    ├── input_manifest.go
    └── output_source_file.go

```
Adding `input_` and `output_` helps conceptualized the flow of data.  And `child_` helps clarify the vagueness of `resources`.
